### ISSUE TITLE
[Meshery Cloud Avatar URL] - Unable to change avatar

### ISSUE THREAD

**Issue by sandramsc** [meshery/meshery#10036]
### Current Behavior

Steps:

1. Access [account profile](https://meshery.layer5.io/account/profile)
2. Change the avatar URL
3. Click "Save changes"
4. Error pops up with no descriptive message
### Expected Behavior

Users should be able to change their avatars by providing an accessible URL. If there is an issue with the provided URL the popup error message should contain a descriptive message that tells the user why.
### Screenshots/Logs

![ppic](https://github.com/meshery/meshery/assets/19821445/786fc981-8852-48d5-8301-1913a9d92e10)

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
Thank you for capturing this, @sandramsc. 

@senali-d, will you investigate?

**Comment by sudhanshutech** [comment]
@sandramsc its most probably cache issue , will you clear your browser cache then try it.

**Comment by sudhanshutech** [comment]
its looking fine:


https://github.com/meshery/meshery/assets/90546692/23f69f41-6c25-4fbe-a952-d65a38e948d6

**Comment by senali-d** [comment]
> Thank you for capturing this, @sandramsc.
> 
> @senali-d, will you investigate?

I just wondering how you would get a error notification without message. Because we can save any image url here.

Btw image from google driver is can not be used as a profile image here. Let's assume it is saved without any issue, but still it doesn't preview as profile image. Because google driver content need permissions for access the data in the driver. (Google have some kind of permission and policy).  @sandramsc So you can try image from any other source.

Actually we can add some validations or helper message kind of thing. Any other thoughts...
