### ISSUE TITLE
[UI] - RTK Migration Designs 

### ISSUE THREAD

**Issue by senali-d** [meshery/meshery#10046]
### Desired Behavior

All the api in the "Designs" page migrate to RTK.

- [ ] Publish design - `api/pattern/catalog/publish` [POST] -> https://docs.meshery.io/reference/rest-apis#api-pattern-catalog-publish @cesartheroman
- [ ] Unpublish design - `api/pattern/catalog/unpublish` [DELETE] -> https://docs.meshery.io/reference/rest-apis#api-pattern-catalog-unpublish @cesartheroman
- [ ] Deploy design - `api/pattern/deploy` [POST] -> https://docs.meshery.io/reference/rest-apis#api-pattern-deploy
- [ ] Un deploy design - `api/pattern/deploy` [DELETE] -> https://docs.meshery.io/reference/rest-apis#api-pattern-deploy

https://playground.meshery.io/configuration/designs

### Mockups

Get some idea how to do migration - https://github.com/meshery/meshery/issues/9985

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by cesartheroman** [comment]
Hi @senali-d I would be more than happy to help out with this issue!

**Comment by cesartheroman** [comment]
@senali-d @sudhanshutech Just wanted to update you both on my progress on this ticket so far since I was only able to start on it today (Feb 6th). I'm documenting the resources I read to try to figure out what files I needed to do work on in the codebase and where they were. As you'll see I have a couple of questions that I'll also look to share during the development meeting tomorrow.
cc: @leecalcote 

### Resources Read
- [Parent RTK Migration Issue for general overview](https://github.com/meshery/meshery/issues/9985)
- [Example migration for Environment + Workspaces](https://github.com/meshery/meshery/pull/10131/files)
- [Example migration for Connections](https://github.com/meshery/meshery/pull/9992)
- [How to **implement** RTK Query example](https://github.com/meshery/meshery/blob/fa40f6302ee47f3ecd8157d74c9ad855a5e300bd/ui/rtk-query/environments.js)
- [How to **call** RTK Query example](https://github.com/meshery/meshery/blob/fa40f6302ee47f3ecd8157d74c9ad855a5e300bd/ui/components/Lifecycle/Environments/index.js)
- [RTK Query Docs](https://redux-toolkit.js.org/tutorials/quick-start)
- [Meshery API Docs](https://docs.meshery.io/reference/rest-apis#api-pattern-catalog-publish)

### Approach on how to begin work and questions based on resources read

1. Identify and complete work needed to implement RTK Query (seems to be in the `ui/rtk-query` directory, for my use case, I’m looking at the Meshery Designs, so `ui/rtk-query/design.js` would be where I think I need to start).
2. Then identify and complete calling the RTK Query defined in the `design.js` file in the first step within the `ui/components/MesheryPatterns.js `file. (I THINK). 
    <img width="724" alt="Screenshot 2024-02-06 at 5 02 17 PM" src="https://github.com/meshery/meshery/assets/60380027/36523692-2d93-483b-bff0-b8107a29c7cc">
- Based on the above screenshot with the request call stack after clicking on the "Designs" tab of Meshery, I figured I need to work within the `MesheryPatterns.js` file. 
- **Question:** Were the Meshery Designs used to be called "MesheryPatterns" and that's why I couldn't find an accompanying "Designs" file in the `components` directory?
3. Since the scope of my ticket is in migrating the following endpoints:
     - `api/pattern/catalog/publish` [POST]:
        - Identified potential work to be done on Line 878 `handlePublish()` function in `ui/components/MesheryPatterns.js` since it uses the `dataFetch()` to the endpoint
     - `api/pattern/catalog/unpublish` [DELETE]:
        - Identified potential work to be done on Line 767 `handleUnpublishModal()` function in `ui/components/MesheryPatterns.js` since it uses the `dataFetch()` to the endpoint

If anyone has any answers to my questions or can tell me if I'm going in the wrong direction, feel free to reply to this comment, otherwise I'll bring it up in tomorrow's meeting! Thanks!
