### ISSUE TITLE
[Extensions] Sections missing capabilities

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10076]
### Current Behavior

<img width="679" alt="Screenshot 2024-01-23 at 1 19 36 PM" src="https://github.com/meshery/meshery/assets/7570704/4f280664-6b8a-4a76-9d10-ed5314cbbda4">

### Environment

- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Meshery Build and Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 UI Design For Meshery Extensions [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 📚 [Meshery Extensibility Providers](https://docs.meshery.io/extensibility/providers)
- ⌨️ [Meshery API Docs](https://docs.meshery.io/extensibility/api)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by AjaxAueleke** [comment]
@leecalcote I was able to pull up Pamela and was able to label and restyle the section. You can't change the section to certain shapes when there is a component in it but I don't think this issue is about that.

I tested this on live playground as well as my local development environment and tested it on Safari as well as Chrome and was not able to recreate the bug.


https://github.com/meshery/meshery/assets/62912869/bac8e016-cc27-43cb-8afd-6ce6568048f2

**Comment by leecalcote** [comment]
Thanks for this, @AjaxAueleke. It may have been that there was a recent release, and that my browser’s cache is emptied.
