### ISSUE TITLE
[mesheryctl] Artifact Hub: `registry generate` not considering source API rate limiting

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10359]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior

Running `mesheryctl registry -import- generate` receives HTTP 429 from Artifact Hub.  

**~/.meshery/logs/registry-generate**

```
status code 429 for https://artifacthub.io/.....
```

### Desired Behavior
The prior script before this `generate` command was considerate of rate limiting. `generate` needs to be considerate as well.

### Environment

- Host OS: Mac
- Meshery Client Version: stable-v0.7.21

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by MUzairS15** [comment]
The mesheryctl command does consider rate-limitting the same way as it was considered in the script.
Because, you might have run the command frequently the rate-limitting might have crossed the threshold.
Previously, almost all of the time the scripts ran in the workflow only once a day hence didn't cross the ratelimitting threshold, this particular rate-limitting problem will always occur if the command is run frequently.

The model-generator workflow uses the same mesheryctl command, and there's has been no rate-limitting issue (as rate-limitting is being handled).

**Comment by leecalcote** [comment]
@Jougan-0, please document the work that has been done here. An update in these two docs is requested:

1. https://docs.meshery.io/project/contributing/build-and-release
1. https://docs.meshery.io/extensibility/integrations/artifact-hub

**Comment by Jougan-0** [comment]
> @Jougan-0, please document the work that has been done here. An update in these two docs is requested:
> 
>     1. https://docs.meshery.io/project/contributing/build-and-release
> 
>     2. https://docs.meshery.io/extensibility/integrations/artifact-hub

Ok sir.

**Comment by leecalcote** [comment]
I believe that this has been completed.

**Comment by MUzairS15** [comment]
Yes
