### ISSUE TITLE
[UI] Local Provider: Designs fail to load

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#10626]
### Current Behavior
On the Designs page, the following error occurs on load:

<img width="625" alt="Screenshot 2024-03-27 at 8 51 50 AM" src="https://github.com/meshery/meshery/assets/7570704/16701014-c7d4-4f71-a40b-dc9e92e7d286">

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Adarsh-jaiss** [comment]
- I was facing this same issue when i was chossing meshery provider as `none` .
- I got deep into the issue to find the root cause of the error and then I got to know that its not fetching the tokenString here in this line https://github.com/meshery/meshery/blob/d77561cac58b4cec3aa4cb7717c9cb4dac78fe97/server/handlers/meshery_pattern_handler.go#L889
- Due to this, an empty string is being passed here : https://github.com/meshery/meshery/blob/d77561cac58b4cec3aa4cb7717c9cb4dac78fe97/server/handlers/meshery_pattern_handler.go#L912  and  **This is the function which is causing this error**


- and again same thing is happening over here : https://github.com/meshery/meshery/blob/d77561cac58b4cec3aa4cb7717c9cb4dac78fe97/server/handlers/meshery_pattern_handler.go#L957   , but this is not showing any error in my console.


Additionally i also looked into this fucntion : https://github.com/meshery/meshery/blob/d77561cac58b4cec3aa4cb7717c9cb4dac78fe97/server/models/default_local_provider.go#L286

if its It converting the the page and pageSize values from strings to unsigned integers using the strconv.ParseUint function, and added these parameters to debug and this was properly working. 
```
func (l *DefaultLocalProvider) FetchAllResults(_, page, pageSize, _, _, _, _ string) ([]byte, error) {
	if page == "" || pageSize == "" {
        return nil, fmt.Errorf("page and pageSize are empty")
    }

	fmt.Println("Fetching results for page 1: ", page)
	fmt.Println("Fetching results for pagesize 1: ", pageSize)

	if page == "" {
		page = "0"
	}
	if pageSize == "" {
		pageSize = "10"
	}
	pg, err := strconv.ParseUint(page, 10, 32)
	if err != nil {
		return nil, ErrPageNumber(err)
	}
	pgs, err := strconv.ParseUint(pageSize, 10, 32)
	if err != nil {
		return nil, ErrPageSize(err)
	}

	fmt.Println("PAGE: ", page)
	fmt.Println("PAGESIZE: ", pageSize)

	return l.ResultPersister.GetAllResults(pg, pgs)
}

```


So now i'm preety sure that this is the function which is causing error and that is due to **empty token string** . Now i need to look, how to fix that empty token issue and make it work. 

Also, please let me know your views on this : @yash37158 @leecalcote

**Comment by Adarsh-jaiss** [comment]
- so I finally i figured it out that the issue was with `pageSize` since it was undefined because we missed to add a number (0) in this useState : https://github.com/meshery/meshery/blob/d77561cac58b4cec3aa4cb7717c9cb4dac78fe97/ui/components/MesheryPatterns.js#L339
- so i fixed the issue And now its working : 
![image](https://github.com/meshery/meshery/assets/96974600/7ce54557-5019-48d6-be54-3d43cf9916d3)
