### ISSUE TITLE
[CI] migrate the e2e testing workflow to use playwright . 

### ISSUE THREAD

**Issue by aabidsofi19** [meshery/meshery#10988]
### Current Behavior

Migrate the meshery ui end to end testing workflow ( currently disabled ) to use the new playwright tests .
the playwright test suite  can be started using make commands .

### Acceptance Tests

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
- Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)
- 🧪 [Meshery Test Plan Spreadsheet](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=0)

**Comment by aabidsofi19** [comment]
@DevRish  yeah thats the right approach .

**Comment by jameshorton2337** [comment]
@DevRish, looks like we've had a misfire on the first PR. Try again and come back quickly or let us know if you're in need of being reassigned, so that another contributor can carry this forward.

**Comment by leecalcote** [comment]
@DevRish you're encouraged to try again. In the meantime, as you work on it, I'll open this up for other contributors to undertake the crux of this issue, which is the conversion from one tool to the next.

**Comment by DevRish** [comment]
Here is my second try at this issue. Summary of changes:

- Migrated all cypress tests except commented out ones (`service_mesh_configuration_management_spec.js` and `configuration_filters_spec.js`) to playwright. Verified passing on my system.
- Used provider `None` for running the tests, because the `Meshery` provider was giving some errors in my local instance, which I haven't been able to fix yet. However, I think the flow of the existing tests are same irrespective of provider chosen.
- The test for visibility of `Service Mesh` section in `indexui.spec.js` is commented out because it was failing on my end, as no such section was indeed visible in the left navigation panel on the local instance.
- The checks to compare response bodies of requests to `/api/system/adapters` and `/api/system/adapter/manage` in `settings.spec.js` was done in the cypress tests, but I have excluded them because I think the request body will differ depending on which adapters the user has active and running, based on the responses I observed.

Please review @leecalcote @jameshorton2337
