### ISSUE TITLE
[Extensions]: Disabled Meshery Catalog Content

### ISSUE THREAD

**Issue by jerensl** [meshery/meshery#12329]
### Current Behavior
Currently when user visit [User Preference](https://playground.meshery.io/user/preferences) pages, and toggle to disabled Meshery Catalog Content it will go back to the enabled toggle

### Expected Behavior
User visit [User Preference](https://playground.meshery.io/user/preferences) pages, and able to disabled the Meshery Catalog Content toggle

### Screenshots/Logs

![screenshot-1728444916134](https://github.com/user-attachments/assets/aa4beb6e-706b-4e25-bf21-eeb6148005aa)

Request:
![screenshot-1728445162738](https://github.com/user-attachments/assets/e8d0afd1-55a8-441f-8aba-8da09a336827)

Response:
![screenshot-1728445291683](https://github.com/user-attachments/assets/58cbe286-ae5c-42b7-b732-973df143e546)

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by dhirajudhani** [comment]
Hey should i work on this issue ?

**Comment by leecalcote** [comment]
@dhirajudhani have you build and run Meshery Server and UI? Do you have a handle on the bug and a proposal as to how to fix? If yes, then yes, let's go.

**Comment by shanukun** [comment]
Meshery Catalogue Content cannot be disabled since it is never enabled. The endpoint `/api/user/prefs` expects a `{"usersExtensionPreferences":{"catalogContent":true}}` to update extension catalogue preferences, however the request only includes `{"catalogContent":true}`.

`usersExtensionPreferences` is also the json tag for extension preferences field in `Preference` struct.


The request query is broken since d555ff250. A simple fix would be to set the `body:  queryArg` in https://github.com/meshery/meshery/blob/d23f42275e58760e739a5e3795fef30acd84ac18/ui/rtk-query/user.js#L31

**Comment by leecalcote** [comment]
@shanukun great. PR?
