### ISSUE TITLE
[mesheryctl] `system config gke`: Error generating config with null input

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#12566]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior
See logs below.

### Screenshots/Logs
```
$ mesheryctl system config gke
Configuring Meshery to access GKE...
Creating a service account in default namespace: sa-meshery-ikzymhhd
serviceaccount/sa-meshery-ikzymhhd created
[clusterrolebinding.rbac.authorization.k8s.io/sa-meshery-ikzymhhd](http://clusterrolebinding.rbac.authorization.k8s.io/sa-meshery-ikzymhhd) created
Getting secret of service account sa-meshery-ikzymhhd on default
jq: error (at <stdin>:11): Cannot iterate over null (null)
Error generating config:exit status 5
```

### Environment

- Host OS: Windows
- Meshery Client Version: stable-v0.7.133

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Tanishq1604** [comment]
Hi @lekaf974  and @leecalcote ,

I noticed that this issue is currently self-assigned. I wanted to check if there’s already progress on it or if I could contribute to resolving it. I've identified some key changes for `GenerateConfigGKE` in `scripts.go` that could address the null secret issue.

If available, I can work on this and update the issue with current screenshots and results after implementing the fix. Please let me know if I can proceed
ScreenShot of how it is now after making some changes 
<img width="540" alt="Screenshot 2024-11-10 at 3 19 47 AM" src="https://github.com/user-attachments/assets/7e3d828d-5145-453b-9f86-77657539a493">

**Comment by leecalcote** [comment]
@Tanishq1604, please contribute.

**Comment by leecalcote** [comment]
@hexxdump FYII

**Comment by Tanishq1604** [comment]
@leecalcote please review this PR #12620 and let me know if any additional changes are needed or not .I have also tried to make it more readable than before so that, It can be more understandable
