### ISSUE TITLE
@kumarabd can we get more specific, please? Will you create a page on docs.meshery.io with the required permissions?

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3021]
@kumarabd, rewrite this issue, please.

@kumarabd can we get more specific, please? Will you create a page on docs.meshery.io with the required permissions?

_Originally posted by @leecalcote in https://github.com/layer5io/meshery/pull/3020#discussion_r638712818_

**Comment by leecalcote** [comment]
@piyushsingariya here is the issue that I mentioned on our `system check` review call.

**Comment by kumarabd** [comment]
Specific permissions are not currently figured yet. Its assigned with admin privilege for now. 
ref:
- https://github.com/meshery/meshery/blob/master/install/deployment_yamls/k8s/service-account.yaml
- https://github.com/meshery/meshery-operator/blob/master/config/manifests/default.yaml#L201-L320

Admin privileges are required because we discovered everything that exists inside the kubernetes cluster and perform CRUD operations on them.

**Comment by leecalcote** [comment]
This documentation never happened. Instead, we've hit our heads on verb assignments or lack thereof.
