### ISSUE TITLE
[CI] Helm: use Meshery release tag as chart version number

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3128]
Can we using the current release tag? We desire for the chart versions to be the same as Meshery's version.

Representative Workflow - https://github.com/meshery/meshery/blob/master/.github/workflows/helm-chart-releaser.yml

_Originally posted by @leecalcote in https://github.com/layer5io/meshery/pull/3076#discussion_r642518699_

**Comment by leecalcote** [comment]
Done!

**Comment by panyuenlau** [comment]
> @panyuenlau you might want to take a crack at this one.

 @leecalcote Sorry I missed this because of a lot of other GitHub notifications, is this still on our to-do list that needs to be addressed?

**Comment by DelusionalOptimist** [comment]
@panyuenlau I thin this still needs to be addressed. :thinking: 
`chart_version` matches to that of Meshery's release however `app_version` doesn't. IMO since `app_version` has already been set to v0.6.0 we should not pull it back albeit it is just informational.
![2021-11-30_00-02](https://user-images.githubusercontent.com/54525605/143923654-9c8a79e5-fed6-4172-a484-d80db07df34e.png)
Once we publish Meshery's v0.6.0 release, we may update the [chart releaser](https://github.com/meshery/meshery/blob/89e928bbfcc8011bc63dc11ca07451cc4bc6b99e/.github/workflows/helm-chart-releaser.yml#L70-L82) workflow and set [app_version](https://github.com/stefanprodan/helm-gh-pages/blob/12f5926e622ccae035cf5a3bb8d67ae6db7dc4b7/action.yml#L43-L45) to be updated in a manner similar to the chart_version, using the triggering release's git tag.

**Comment by leecalcote** [comment]
@DelusionalOptimist, spot on. @panyuenlau, completely understand. Yes, please.
