### ISSUE TITLE
[UI] Performance not active in UI

### ISSUE THREAD

**Issue by piyushsingariya** [meshery/meshery#3175]
#### Description

When clicked on profiles, Performance isn't blue(active)

#### Expected Behavior

Performance should turn blue when clicked on Profiles just like Conformance is blue
![image](https://user-images.githubusercontent.com/50979887/121392646-356ebc80-c96d-11eb-9094-ecfaeea71c33.png)

#### Screenshots/Logs

![image](https://user-images.githubusercontent.com/50979887/121392493-153efd80-c96d-11eb-9760-7c9490b28e44.png)

#### Environment:
- Meshery Version: 
- Kubernetes Version: 
- Host OS:
- Browser: 

---

**Contributor Resources:**
- (Contributing Docs](https://docs.meshery.io/project/contributing)

**Comment by ankitzm** [comment]
Can I give this a try.

**Comment by debjani1413** [comment]
Here you go @ankitzm :)

**Comment by ankitzm** [comment]
Can you please tell me, "how can I get to the page that you have provided in the screenshot.

**Comment by leecalcote** [comment]
Hopefully, these instructions help - https://docs.meshery.io/project/contributing-ui

**Comment by sudo-NithishKarthik** [comment]
@ankitzm , In case you still haven't got the page, it's in **'/ui/components/Navigator.js'** file.

**Comment by ankitzm** [comment]
> @ankitzm , In case you still haven't got the page, it's in **'/ui/components/Navigator.js'** file, hope it helps ✌🏽

Thanks for the help 😊

**Comment by ankitzm** [comment]
After a lot of brainstorming and understanding the project I found that the problem is not with the Performance link.
The problem arises due to some old codes, which I have attached below

![image](https://user-images.githubusercontent.com/66105983/122637049-2e347500-d10a-11eb-947a-8a2b9d338f02.png)

The href link in both "Conformance" and "SMI Results" are same, thats why they both are shown in blue shade when clicked.
But "Performance" and "Profile" have different href link. "Profile is a subpage of "Performance".

It is the problem with styling which I am unable to find.

**Comment by sudo-NithishKarthik** [comment]
Yes, i agree with what @ankitzm is saying. I believe that there is a solid reason for both *Conformance* and *SMI Results* having the same path as there is a code comment stating that it is a temporary thing.

<img width="331" alt="Screenshot 2021-06-21 at 8 35 26 AM" src="https://user-images.githubusercontent.com/75248557/122701833-b8481f00-d26b-11eb-8229-ef196cf36c45.png">

So, the fact that conformance and smi_results being highlighted at the same time is because of this(having same path) and not the motive of the design.

Although, if we still want to make it like that, we could do it. 

@leecalcote  or @piyushsingariya , can anyone of you confirm if this is what we want?
