### ISSUE TITLE
[Helm] Charts showing invalid version number on artifacthub

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3199]
#### Description
On https://artifacthub.io/packages/helm/meshery/meshery, Meshery charts display invalid version numbers.

#### Screenshots/Logs
<img width="953" alt="Screen Shot 2021-06-13 at 6 22 36 PM" src="https://user-images.githubusercontent.com/7570704/121824823-7ff57f00-cc74-11eb-99e8-e00b7663a719.png">

#### Workflow
- https://github.com/layer5io/meshery/blob/master/.github/workflows/helm-chart-releaser.yml

---

**Contributor Resources:**
- (Contributing Docs](https://docs.meshery.io/project/contributing)

**Comment by anurag8546** [comment]
Sir, Where will I find the code of this file?
I've cloned the repo, but unable to find the source code of this page.

**Comment by anurag8546** [comment]
So, This issue here in the "version-2.1.2 " is  basically because of the "Image inserted (https://img.shields.io/badge/Version-2.1.2-informational?style=flat-square) there in the source code, which can be either changed or can be updated by changing in the HTML code.
and the issue there in the right bottom  the "Dependencies section " is simply because of the HTML code, which is not updated after the update in version, which can also be solved easily.
![imp1](https://user-images.githubusercontent.com/76533034/122616230-9bfb8500-d0a7-11eb-890c-f2dd15c7d070.PNG)
![imp2](https://user-images.githubusercontent.com/76533034/122616238-9e5ddf00-d0a7-11eb-9b07-61ea056825c1.PNG)

Kindly help me finding the source code of this page, so that I can fix it.

**Comment by anurag8546** [comment]
@leecalcote sir, Kindly look into it.

**Comment by leecalcote** [comment]
I think this will take a verbal explanation. SVGs can be dynamically generated to include text. The fix for this issue will not be done in Artifact Hub, but in GitHub workflow in this repo. Join the biweekly CI meeting for assistance.

**Comment by anurag8546** [comment]
> I think this will take a verbal explanation. SVGs can be dynamically generated to include text. The fix for this issue will not be done in Artifact Hub, but in GitHub workflow in this repo. Join the biweekly CI meeting for assistance.

Okay!

**Comment by leecalcote** [comment]
GitHub workflow - https://github.com/meshery/meshery/blob/master/.github/workflows/helm-chart-releaser.yml
Helm charts - https://github.com/meshery/meshery/tree/master/install/kubernetes/helm/meshery
