### ISSUE TITLE
[UI] Navigation highlight not working properly for subsections under Management section

### ISSUE THREAD

**Issue by sudo-NithishKarthik** [meshery/meshery#3268]
#### Description
Subsections under **Management** section are not getting highlighted when navigated to those sections. But rather, **Management** is getting highlighted

#### Expected Behavior
The navigated subsection should be highlighted. 

#### Screenshots/Logs

https://user-images.githubusercontent.com/75248557/123373245-b00d1e00-d5a2-11eb-8cc3-c6ce42317257.mov

#### Environment:
- Meshery Version: stable-v0.5.26
- Kubernetes Version: v1.19.7
- Host OS: Big Sur
- Browser: Brave 

---

**Contributor Resources:**
- (Contributing Docs](https://docs.meshery.io/project/contributing)

**Comment by nishit-prasad** [comment]
Hello, I am a newcomer to open source contributions and would like to work on this.

Currently reviewing the documentation/guidelines and setting up my environment.
I have joined the Meshery Slack workspace.

Thanks!

**Comment by sudo-NithishKarthik** [comment]
Welcome @nishit-prasad 🥳 , there are a lot of people in the community willing to help people. Just ping on slack if you face any difficulties ✌🏽

**Comment by nishit-prasad** [comment]
Thank you! I really appreciate it!

**Comment by nishit-prasad** [comment]
@sudo-NithishKarthik 
I think I found the root cause.
Part of the highlight logic is tied up with `link` value of the subsections (children).
https://github.com/layer5io/meshery/blob/master/ui/components/Navigator.js#L334

Setting them `true` seems to fix it. Wanted to make sure whether they're any issues with this change before I commit in my scratch branch?
I have posted this concern in **#meshery-ui** slack channel.
_________________
_________________
Also:
(If you refer screen recording)
I also noticed that the subsection **SMI Results** under **Conformance** have same href URLs.
So, if you select **SMI Results** subsection, you will see both **Conformance** and **SMI Results** highlighted.
That's because both have _same_ **href** links (and another part of highlight logic is tied with it).

So the question is, if we have a distinct URL in place - I can add the fix in this or I am okay with anybody raising as a new issue.

Please advise.
