### ISSUE TITLE
`Get Token` cannot return auth token when the user is not signed in with any providers

### ISSUE THREAD

**Issue by Abhishek-kumar09** [meshery/meshery#3293]
#### Description

The `Get Token` menuItem on the meshery user interface returns the auth token provided by the signed in providers like google, github etc. But in case the user is not logged in with any provider but only as a none user it can't actually return any token.
Currently it is returning a file with empty json fields.
What if that option can be disabled and a tooltip can be inserted that shows `login with providers to get auth token`.

#### Screenshots/Logs

![image](https://user-images.githubusercontent.com/48255244/123799031-69eaee00-d905-11eb-89eb-51817980a844.png)
Downloaded Token (Which is empty and may not serve the purpose that is thought before clicking the getToken button)
```
{"meshery-provider":"None","token":""}
```

#### Environment:
- Meshery Version: edge-v0.5.23
- Kubernetes Version: 1.20.7
- Host OS: Ubuntu 20.04
- Browser: Firefox

---

**Contributor Resources:**
- (Contributing Docs](https://docs.meshery.io/project/contributing)

**Comment by utkarsh-pro** [comment]
Hi @Abhishek-kumar09, thanks for opening up this issue however the token _is_ actually there. It just happens to be an empty string when the provider is "None". So this issue is technically _not_ a bug. 

This could be a security issue **if** a user exposes meshery deployment to the internet. To handle such scenarios can you please close this issue and open up another issue for a Design Spec on securing the Local Provider Token (this issue will have label - `issue/design-required`)

**Comment by Abhishek-kumar09** [comment]
Sure, gott the point.
Though I don't entirely got the thing you are asking for maybe due to less knowledge about meshery at the point.
