### ISSUE TITLE
[mesheryctl] CRUD for tokens

### ISSUE THREAD

**Issue by navendu-pottekkat** [meshery/meshery#3508]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

Users can have multiple tokens and reference them in their meshconfig (~/.meshery/config.yaml) file. This means that a user can have multiple tokens and can use different tokens for different contexts.

However, right now the users have to manually edit their config files in-order to change the token used in a particular context and even add new tokens, change the location of the token etc.

#### Desired Behavior

Similar to channel and context constructs in the meshconfig, mesheryctl should also support CRUD actions for tokens:

Add a new token to the meshconfig:

* `mesheryctl system token add <token name> -f <optional: path to the token, defaults to auth.json>`

Delete token:

* `mesheryctl system token delete <token name>`

Set token (of current-context or context passed in with the `--context` flag):

* `mesheryctl system token set <token name>`

List tokens:

* `mesheryctl system token list`

View tokens:

* `mesheryctl system token view <token name>` (if token name is not passed, then the token of the current-context)

Power/advanced users can directly edit the meshconfig for use cases other than these.

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by navendu-pottekkat** [comment]
@meshery/mesheryctl-contributors please update the description if there are any missing/wrong usecases.

**Comment by DarthBenro008** [comment]
Hi @navendu-pottekkat , I'd like to work on this and give it a shot! 😃

**Comment by Revolyssup** [comment]
@navendu-pottekkat  Is this the desired behavior? Please suggest changes otherwise.

# Add
## before
![1_before](https://user-images.githubusercontent.com/43276904/125760912-ff606c91-91ea-4fed-9a68-6b680b727d2e.png)

## after 
![1_after1](https://user-images.githubusercontent.com/43276904/125760934-386ac5e1-3966-4e44-aa05-dcfbb1a718b1.png)
![1_after2](https://user-images.githubusercontent.com/43276904/125762642-9af5b12c-7de3-49eb-b573-41c6cb2e8c3f.png)


## before
![2_before](https://user-images.githubusercontent.com/43276904/125761179-cdf35357-bada-496a-a8ea-c72c7856c1e7.png)
## after
![2_after1](https://user-images.githubusercontent.com/43276904/125761208-eee134df-c36c-4ad9-a8cd-f01d4214cd40.png)
![2_after2](https://user-images.githubusercontent.com/43276904/125762788-ab45006a-7209-4be5-bfe1-6ad74dadfb0e.png)

# Delete
## before
![3_before1](https://user-images.githubusercontent.com/43276904/125761283-5d60a803-3a93-4074-b40f-6d250baba657.png)
## after
![3_after1](https://user-images.githubusercontent.com/43276904/125761300-74467c69-e439-4df4-acc1-0e1d7a431daa.png)
![3_after2](https://user-images.githubusercontent.com/43276904/125761325-a4a677e3-72bd-4542-9fb7-51dc10dfb52f.png)

# Set
## before
![4_before](https://user-images.githubusercontent.com/43276904/125761386-28aa68ed-6644-4a1c-b9f1-0b150e376343.png)
## after
![4_after1](https://user-images.githubusercontent.com/43276904/125761423-fe327c44-7b51-4ba7-a505-73fc1a6d63fd.png)
![4_after2](https://user-images.githubusercontent.com/43276904/125761429-b643a35c-e5bd-44bf-a94b-dffce8056ec0.png)

## For invalid context
![8](https://user-images.githubusercontent.com/43276904/125761917-62d128ce-9a41-4963-a6d1-f379310c7638.png)

# List
![5](https://user-images.githubusercontent.com/43276904/125761488-1450d2df-7a72-4f4d-95fc-9ca51f6aeacf.png)

# View
![6](https://user-images.githubusercontent.com/43276904/125761574-18abcb6f-c471-456d-97b3-2ae0de770876.png)
![7](https://user-images.githubusercontent.com/43276904/125761593-cdbead61-6c0d-4e33-8ff6-e0faa8d8767e.png)

## when the token is not specified in context
![9](https://user-images.githubusercontent.com/43276904/125762305-c90ea119-0c9b-4a6b-be34-9749698dd4fe.png)
![9 2](https://user-images.githubusercontent.com/43276904/125762331-73084a14-fdf1-4036-91fc-a646d9a074a0.png)

**Comment by navendu-pottekkat** [comment]
@Revolyssup I think these are correct, could you open up a PR on this so that we can test this out?

**Comment by navendu-pottekkat** [comment]
@DarthBenro008 You could check out [these open issues ](https://github.com/meshery/meshery/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee)and see if something interests you.
