### ISSUE TITLE
[UI] Safari icons scaling issue

### ISSUE THREAD

**Issue by sudo-NithishKarthik** [meshery/meshery#3957]
#### Current Behavior
Icons that we use in Meshery UI does not scale well with Safari.
Look at [#1146](https://github.com/meshery/meshery/issues/1146) for more clarity.

#### Desired Behavior
Icons should be scaling well with safari on Zoom in/out.

#### Implementation
This is already being fixed for the header icons in [#2934](https://github.com/meshery/meshery/pull/2934) , the same has to be done for all the other icons.
A Higher Order Component has to be created that will incorporate these changes and serve as a wrapper around `Icon` to be reused everywhere in Meshery UI

#### Environment

- Browser:  Safari 
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Aisuko** [comment]
Hi @sudo-NithishKarthik, I guess this can be a good first issue right? If so, please help add the `good-first-issue` label, thanks.

**Comment by sudo-NithishKarthik** [comment]
Definitely, thank you @Aisuko 👍🏽

**Comment by DanielLivingston32** [comment]
@sudo-NithishKarthik I would like to work on this.

**Comment by DanielLivingston32** [comment]
@sudo-NithishKarthik 
After going through the code base this is what I came up with.

Make a new file style.js under ui/components with the following code
`export const iconStyle =  { icon : { fontSize : '1.5rem', height : '1.5rem', width : '1.5rem', } , }`

Then we can just import this file and use it as follows:

`import React from 'react';
import PropTypes from 'prop-types';
import AppBar from '@material-ui/core/AppBar';
import Grid from '@material-ui/core/Grid';
import Hidden from '@material-ui/core/Hidden';
import IconButton from '@material-ui/core/IconButton';
import MenuIcon from '@material-ui/icons/Menu';
import Toolbar from '@material-ui/core/Toolbar';
import Typography from '@material-ui/core/Typography';
import { withStyles } from '@material-ui/core/styles';
import { connect } from 'react-redux';
import NoSsr from '@material-ui/core/NoSsr';
import Link from 'next/link';
import SettingsIcon from '@material-ui/icons/Settings';
import MesheryNotification from './MesheryNotification';
import User from './User';
import { iconStyle } from './style';
// import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
// import { faHome } from '@fortawesome/free-solid-svg-icons';

const lightColor = 'rgba(255, 255, 255, 0.7)';

const styles = (theme) => ({
  ...iconStyle,
  secondaryBar : { zIndex : 0, },}`

**Comment by DanielLivingston32** [comment]
Shall i proceed with a PR?

**Comment by sudo-NithishKarthik** [comment]
Hmm, your approach seems valid, but it is not dynamic, we do not want every icon to be have dimensions of `1.5 rem`, also, it requires the class `icon` to be applied to every icon component 🤔

**Comment by sudo-NithishKarthik** [comment]
Instead, creating a HOC, that takes in the icon component and returns it after setting the `height` and `width` to be the same as `fontSize` would be more convenient.

**Comment by DanielLivingston32** [comment]
Alright, will work on implementing this.

**Comment by DanielLivingston32** [comment]
@sudo-NithishKarthik 
I tried implementing with HOC but since there are many icons there was a hassle making it.
I came up with this other idea based on this link. [https://material-ui.com/components/icons/#icon-font-icons](https://material-ui.com/components/icons/#icon-font-icons).

For this I made a DisplayComponents.js file under ui with the following code:

`import Icon from '@material-ui/core/Icon';`

`export const renderIcon = ({ iconName, fontSize, className }) => {`
`  return (`
`    <Icon`
`      style={{ fontSize : { fontSize }, height : { fontSize }, width : { fontSize } }}`
`      className={className}`
`    >{iconName}</Icon>`
`  );`
`}`

Usage:
Now i can just replace settings icon from header.js with the below code:
`<div data-test="settings-button">`
`                    <IconButton color="inherit">`
`                      <Link href="/settings">`
`                        {`
`                          renderIcon({ iconName : 'settings', fontSize : '10rem' })`
`                        }`
`                      </Link>`
`                    </IconButton>`
`                  </div>`


The only issue that I face with this approach is that I need to add 
`<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />`
in index.html but i couldn't find that in the code base.


Cons of this Approach:
-> Imports all the icons
-> Change of implementation for all icons is required.

**Comment by sudo-NithishKarthik** [comment]
There are some tweaking needed in this code

**Comment by DanielLivingston32** [comment]
Alright. I actually took the header.js file as a reference. So I thought the default material UI icons were used in the codebase.

**Comment by sudo-NithishKarthik** [comment]
Yes, default Material UI icons are being used, which are SVG Icons

**Comment by DanielLivingston32** [comment]
Oh ok, now I get it. The renderIcon method imports Font icons rather than SVG. I will look into it.
