### ISSUE TITLE
Can Meshery replace my current istio and linkerd?

### ISSUE THREAD

**Issue by nathanawmk** [meshery/meshery#3961]
Can Meshery replace my current istio and linkerd?

**Comment by Aisuko** [comment]
Hi @nathanawm, Welcome to the project. I'm afraid not about your question. As you know that the meshery community maintains many adapters for Service-mesh products, and will deploy them in Helm way, the location of the repo(https://github.com/meshery/meshkit/tree/master/utils/kubernetes). So, we do not check the service mesh in your cluster, because of their many different ways for installing the service mesh.
