### ISSUE TITLE
[mesheryctl] `system config eks` fails to find `aws` cli in path

### ISSUE THREAD

**Issue by DelusionalOptimist** [meshery/meshery#3995]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
mesheryctl fails to find `aws` cli in path even though it is present.

#### Desired Behavior
`mesheryctl system config eks` should connect meshery successfully with the cluster.

#### Possible causes
[This](https://github.com/meshery/meshery/blob/48cd283b9d3ebb7993f5dcbd0a7d09c332030fbb/mesheryctl/pkg/utils/scripts.go#L147) is very hacky and executes the command using `sh` which might not be having the `aws` cli on path and thus causing this error.

#### Environment

- **Host OS: WSL2**
- Meshery Server Version: stable-latest
- Meshery Client Version: v0.5.49
- Platform: EKS

---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by krithikvaidya** [comment]
Hi :), So like @DelusionalOptimist mentioned, are we looking to interact with the cloud services within mesheryctl using the SDKs for Go instead of running the shell commands? If yes, I could work on modifying the related code [here](https://github.com/meshery/meshery/blob/48cd283b9d3ebb7993f5dcbd0a7d09c332030fbb/mesheryctl/pkg/utils/scripts.go) and [here](https://github.com/meshery/meshery/blob/48cd283b9d3ebb7993f5dcbd0a7d09c332030fbb/mesheryctl/internal/cli/root/system/config.go) to use the SDKs instead.

**Comment by DelusionalOptimist** [comment]
Thank you @krithikvaidya for showing interest here and also pinging me in slack.
Since you've told that you're willing to do it even after knowing about the prerequisites (an EKS), I'll assign this to you. :+1:

**Comment by krithikvaidya** [comment]
Thanks for assigning me. I'm having some issues with my MFA on AWS, so I'll get started once that's resolved :)
