### ISSUE TITLE
[API] Paginate Patterns, Apps, Filters

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4142]
#### Current Behavior
A fully loaded Meshery Server has thousands of pattern components. 

#### Implementation
Enhance `/api/oam/workload` to offer pagination

#### Logs

https://user-images.githubusercontent.com/7570704/132809417-d0b19b1e-06d7-4906-8c12-4338e2513289.mov

#### Acceptance Criteria

1. All three resources should have pagination available on their queries.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@Abhishek-kumar09 Is this something that you're able to do?

**Comment by leecalcote** [comment]
@dhruv0000 @bariqhibat @utkarsh-pro  do we have a standard approach here, yet?

**Comment by Abhishek-kumar09** [comment]
Need investigation but what I can infer from the logs here, it is not due to the overflowing of patterns, but certainly due to continuous re-rendering and fetching, maybe there is data leak issue here(maybe due to wrong call to useEffect), it is also possible that the schema is unparsable thus not rendered.

**Comment by Abhishek-kumar09** [comment]
![image](https://user-images.githubusercontent.com/48255244/135732019-8a8d0385-f9fe-44c1-971d-27b4631bb652.png)
The api is throwing endless workloads :(

**Comment by utkarsh-pro** [comment]
@Abhishek-kumar09 I'd be addressing this issue in a coming PR. Thanks for looking into it.

**Comment by bariqhibat** [comment]
Can we close this? @leecalcote

**Comment by Abhishek-kumar09** [comment]
I think yes.
- The patterns, filters, and applications support paginations.
- The schema coming from the server for adapter configuration doesn't contains pagination, actually that can't  be paginated either. But it strongly requires enhancement in terms of fetching only those resources which are visible on UI.

Currently around 8 Mib of data is fetched and processed on frontend for the RJSF forms, which is actually not required since frontend is only consuming 5-10% of coming data. 90% of processing and server resources is going waste.

**Comment by utkarsh-pro** [comment]
@Abhishek-kumar09 `?trim=true` with the lazy loading in the UI not helping here?

**Comment by Abhishek-kumar09** [comment]
forgot to add trim=true
trim removes `oam_ref` from all the schema right, it helps still the size is vast, but at least UI is not breaking. Thanks a lot.

**Comment by utkarsh-pro** [comment]
@leecalcote, do we still need this? We already have trimming in place. Do you foresee any usage for paginating the OAM components?

**Comment by leecalcote** [comment]
@utkarsh-pro no, I think you're right. Let's shut this one down.
