### ISSUE TITLE
[UI/API] Replace Fetch with Axios

### ISSUE THREAD

**Issue by Abhishek-kumar09** [meshery/meshery#4359]
#### Current Behavior
We are using fetch to handle and manage all our requests and responses in react, and it comes with a lot of uncertanities. We have already seen problems parsing data implicitly. The worst part is it comes with bad error handling and extra boiler-plate code to do simple thing.
Axios is industry standard for making and getting requests and responses, helps with automatic json serializations, backward compatibility and a lot of other shiny features too that may get in use.
Just in case: a comparison article between [axios and fetch](https://blog.logrocket.com/axios-or-fetch-api/)

I think replacing axios will take off a lot of uncertanities and may greatly help managing req and responses.
---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by ujju20** [comment]
Can I work on this issue I have some experience in Javascript and with Axios also?

**Comment by sudo-NithishKarthik** [comment]
Yes. I agree that **axios** is better than **fetch** in terms of the Application Programming Interface and some other features. But for Meshery UI, I am _not convinced_ that we should switch to **axios** _now_ because,

1. The task is big and is prone to errors.
2. We are using `isomorphic-fetch`, so the backward compatibility of axios is no more a selling point.
3. I am afraid we won't be utilising the full potential of axios as we will be using **GraphQL subscriptions** for the most part in the future.

So, I feel that it's not completely worth it to switch to `axios`, but again, it's just how _I_ see it.

**Comment by Abhishek-kumar09** [comment]
Awesome pointers @sudo-NithishKarthik,
Personally I felt some problems with handling requests and responses. Definately, it requires a effort to replace axios with fetch where we have to tests absolutely all the endpoints to be working perfectly. But I think it would be a good go, since it's a more standard approach providing benefits of better error handling. Error handling is one of  the prior issue right now, I see a lot of places where I get something weird in the responses and snackbar sometimes it's not predictable. Axios instead gives a more predictive schema for handling requests and responses. Definately, we may not be utilising it wholly, but this is something I believe a good move since we will be definitely be incoropating those in future. 
But definitely, this is a less prior right now and we have more prior work already been scheduled.

**Comment by sudo-NithishKarthik** [comment]
Yep @Abhishek-kumar09 , this is something that we can work on as a part of UI codebase refactor.

**Comment by RajGM** [comment]
Hi @Abhishek-kumar09 
I would like to work on this.

**Comment by acald-creator** [comment]
bump

Since we are now upgrading to Next.js 12/13, Next.js currently supports fetch natively, which means that Next.js takes care of the polyfill for fetch.

Seeing as how this issue has been open for nearly two years, and times have changed since then, I want to revive this issue to raise awareness that Next.js has better support for fetching data, but there are several options we can consider.

Next.js already use `getServerSideProps` and `getStaticProps` as a way to retrieve data at either build time or static time.

React has also moved to suggesting to use React function components which means using hooks more, and we have the opportunity to call `dataFetch` via a React custom hook now.

There are several libraries like SWR that works with Next.js, and react-query that could help in this case as well.

SWR also has examples with using Axios, but since the intent was to move to an updated version of `@reduxjs/toolkit`, we may need to reconsider the use of querying data, along with Relay Framework.
