### ISSUE TITLE
[mesheryctl]: Improve the logging of the utility used to start meshery ui in browser

### ISSUE THREAD

**Issue by Nikhil-Ladha** [meshery/meshery#4907]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

After starting meshery using the `mesheryctl system start` command, mesheryctl tries to
open the UI on the browser unless it succeeds. And, in case there are any errors while doing so,
those are logged into the terminal in a _not-so-user-friendly_ fashion.
Sample:
```
Opening Meshery (http://localhost:9081) in browser.
[nladha@nladha ~]$ Opening in existing browser session.
[770630:770630:0100/000000.273173:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
```

#### Desired Behavior

The error logging could be improved in case the utility fails to start meshery UI using the obvious method.

#### Environment

- Host OS: Linux (Fedora 34)
- Meshery Server Version: v0.6.0-rc-3
- Meshery Client Version: v0.6.0-rc-3
- Platform: Docker

---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Nikhil-Ladha** [comment]
@piyushsingariya ^^

**Comment by theBeginner86** [comment]
I'd like to give it a shot 😁

**Comment by theBeginner86** [comment]
Sorry, I'm unable to fix this bug. I'll remove my assignment so that someone else can take this up 😅

**Comment by theBeginner86** [comment]
Though I wanted to share a few resources which I came across while I was researching for this issue.

This seems a known issue with the Linux systems and browser's GPU acceleration. Moreover, I think that the error is not printed by the browser pkg but printed by the Linux system due to some internal problem with opening the browser. So not sure whether we can actually solve this problem on our side.
https://simpleit.rocks/linux/ubuntu/fixing-common-google-chrome-gpu-process-error-message-in-linux/
https://bugs.chromium.org/p/chromium/issues/detail?id=264818
https://github.com/kubernetes/minikube/issues/12687

Also wanted to ask one thing, can we implement something like this: https://github.com/kubernetes/minikube/blob/master/cmd/minikube/cmd/dashboard.go#L122
https://github.com/kubernetes/minikube/blob/v1.25.1/pkg/minikube/browser/browser.go
wherein we check if the system is `Linux` and if `xdg-open` cmd is installed then call `browser.OpenURL(url)` otherwise simply print some error message(or link to the URL) and if the system is not `Linux` then call `browser.OpenURL(url)` as other systems are not facing this error message

// @piyushsingariya

**Comment by piyushsingariya** [comment]
@theBeginner86 we won't able to do that implementation that you suggested. the current implementation works irrespective of an OS, and that's what we want for a long time, it though opens a stream after executing the operation, maybe the package itself provides an option to not open these streams, did you check in this direction?

**Comment by ashutosh887** [comment]
Hey @leecalcote  Should I try on this one? @Nikhil-Ladha @piyushsingariya @theBeginner86 @blake @lucj

**Comment by piyushsingariya** [comment]
sure!

**Comment by ashutosh887** [comment]
Can you tell me which File should I work on @piyushsingariya 
I am just trying to start learning about the file structure of the project

**Comment by theBeginner86** [comment]
@ashutosh887 
You need to check out the `mesheryctl` folder for working and improving mesheryctl.
For this particular issue, the error comes from this line: https://github.com/meshery/meshery/blob/b2ca6e4af20d268bda36813882f7960b17490e20/mesheryctl/internal/cli/root/system/dashboard.go#L103

**Comment by ashutosh887** [comment]
Thanks @theBeginner86
