### ISSUE TITLE
[UI] Multi-Cluster: GraphQL Subscription for K8s Context Switcher

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5850]
#### Current Behavior
When a user removes a Kubernetes context from the context switcher and disconnects Meshery Server from that context, the list of connected contexts remains unchanged despite the fact that Meshery Server no longer manages that context.

#### Desired Behavior
The list of connected contexts should be dynamically updated through GraphQL subscription and not require the user to refresh the screen or navigate to a new page to update the list of contexts.

#### Screenshots

<img width="211" alt="Screen Shot 2022-07-19 at 5 51 26 PM" src="https://user-images.githubusercontent.com/7570704/179861875-04a02468-4fce-40f2-86d1-31aabfeb70dc.png">

<img width="455" alt="Screen Shot 2022-07-19 at 5 51 33 PM" src="https://user-images.githubusercontent.com/7570704/179861878-c11ad2f4-f5eb-40b7-8ba8-3ef201e24695.png">

#### Acceptance Tests
1. User clicks to disconnect the context, then confirms removal, and then sees the context disappear from the Kubernetes context switcher.

<img width="207" alt="Screen Shot 2022-07-19 at 5 56 47 PM" src="https://user-images.githubusercontent.com/7570704/179861986-cedbfcd4-6c65-4f79-b556-52a962281410.png">

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by pk-218** [comment]
I am trying to reproduce this issue here in this video -

[multi-cluster-removal-error.webm](https://user-images.githubusercontent.com/53428217/187955096-e7a62a3c-0e4c-4900-afd7-35e773aef8f5.webm)

The context does get removed from the K8sContextMenu component but this throws an error - 

![multi-cluster-removal-error](https://user-images.githubusercontent.com/53428217/187955627-98c42fb7-17cb-4e35-8715-aea9b18643ea.PNG)

If this is the same issue being faced here, I can work on resolving this.

@leecalcote

**Comment by leecalcote** [comment]
I think this issue has been resolved, but it would be great if a contributor could verify.

**Comment by Freedisch** [comment]
@leecalcote, I confirm
