### ISSUE TITLE
[UI] Adapter versions not being displayed

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6245]
#### Desired Behavior
Each Meshery Adapter should have the adapter version number displayed in parentheses in the tool tip of each adapter chip.

#### Screenshots/Logs
<img width="254" alt="Screen Shot 2022-09-23 at 4 19 25 PM" src="https://user-images.githubusercontent.com/7570704/192058439-9daef472-95d6-462f-9c02-c7b3dcfc7b44.png">

#### Environment

- Browser: Safari
- Host OS: Mac
- Meshery Server Version: stable-v0.6.9
- Meshery Client Version: stable-v0.6.9
- Platform: Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@theBeginner86 will you confirm that the issue is UI-side, not Adapter-side?

**Comment by theBeginner86** [comment]
I've updated the adapters that urgently require fixing due to either outdated Dockerfiles or incorrect tags in the multiplatform workflow because of which they were unusable in `stable-latest`.

The rest of the adapters just require 2 line changes in the workflow for this Meshery UI issue to be fixed. I'll open `good-first-issue` (with Hacktoberfest label) for new contributors to chime in 👍
