### ISSUE TITLE
[UI] After starting meshery, the UI is not accessible

### ISSUE THREAD

**Issue by bluedog13** [meshery/meshery#6621]
#### Current Behavior

1. Start meshery 
```
$ mesheryctl system start                           
Starting Meshery...

Meshery deployed on Kubernetes.
Meshery is starting...
Opening Meshery (http://localhost:31611) in browser
```

The UI is not accessible

Also unable to get the token
```
$ mesheryctl system config minikube --token .
Configuring Meshery to access Minikube...
Error getting context: Authentication token not found. Login with `mesheryctl system login` or supply a valid user token using the --token (or -t) flag.


$ mesheryctl system login                         
authentication failed: Get "http://localhost:31611/api/providers": dial tcp [::1]:31611: connect: connection refused
```

#### Desired Behavior

Should be able to install and start using meshery

#### Screenshots/Logs

<img width="805" alt="Screen Shot 2022-12-02 at 3 37 41 PM" src="https://user-images.githubusercontent.com/11997472/205393713-f8303695-5fd2-4d2a-880c-ee674ee8cf3c.png">

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: unavailable
- Meshery Client Version:v 0.6.30
- Platform: Docker Kubernetes

```
$mesheryctl version      
                           
      	VERSION    	GITSHA
Client	v0.6.30    	6d124bf47
Server	unavailable	unavailable
Unable to communicate with Meshery server.Get "http://localhost:31611/api/system/version": dial tcp [::1]:31611: connect: connection refused.See https://docs.meshery.io for help getting started with Meshery

Checking for latest version of mesheryctl...

  v0.6.30 is the latest release.
```

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by PratikforCoding** [comment]
Try localhost:9081

**Comment by bluedog13** [comment]
I see the same problem/behavior with localhost:9081 as well.

**Comment by bluedog13** [comment]
Yes, I have docker desktop.

But I am running minikube inside docker and running meshery inside Kubernetes cluster itself (in-cluster) mode.


Perhaps what you are asking me is to install the meshery extension inside docker and try using that. If I do that, I can see the meshery UI but it's not able to detect the k8s cluster.

**Comment by PratikforCoding** [comment]
there is a kubernetes option in preferences, turn that on. There is a option to set up cluster when you run docker desktop, enable it. don't run minikube just start the docker desktop after configuring this settings and then try localhost:9081

**Comment by bluedog13** [comment]
I'll try that and update here. 

Any reason why it does not work with minikube or kind cluster both running inside docker? The documentation does not specify that meshery has to be exclusively used with docker k8s setup for this to work. 

Also, we have been using kind cluster for all our poc's and not everyone in our team has docker desktop. 

Thanks.

**Comment by PratikforCoding** [comment]
No, I don't know any particular reasons, I tried many times various way but only this worked, you can ask the maintainers on dev call.

**Comment by theBeginner86** [comment]
Hi @bluedog13 

Thanks for raising this issue.
There are a couple of pointers that do get overlooked sometimes considering it’s not explicitly stated in docs or error logs for mesheryctl.

1. Meshery is a multiple Kubernetes manager and irrespective of the type of Kubernetes cluster, it does auto-detect available K8s clusters in your environment from the `kubeconfig` in your local file system. You can always pass a custom `kubeconfig` from the settings page.
2. Meshery, as a Cloud Native manager, have some custom controllers. For these controllers to communicate within themselves, they use K8s services, one of them is meshery-broker of type `LoadBalancer`. That means, its external IP address needs to be readily exposed so that it can communicate well with every component of Meshery.
3. The challenge with `Minikube` and `Kind` clusters is the loadbalancer which usually doesn’t come out of the box and Meshery provides its users with the freedom to set up networking in their style. Hence networking for such types of deployments is more involved.
A couple of options that I prefer are:
3.1. Use minikube add-on for MetalLB that would provide you with loadbalancer. `minikube addons enable metallb`
3.2. Use minikube tunnel to expose your services. `minikube tunnel`
3.3. For `kind`, I prefer installing MetalLB with custom configmap.
4. But incase you choose docker-desktop then such networking comes out of the box. That's the reason that some contributors in the community prefer it over other options. But either way the experience is exactly same.
5. For `mesheryctl`, there is a command: `mesheryctl system dashboard` which is designed to automatically open Meshery UI onto the default browser. You may try that too.


I'll take a note of few things that should be improved to increase user productivity:
1. Improve docs with more information regarding setup installation
2. Improve `mesheryctl` err logs.

I'll open GitHub issues to track the progress of these updates.


In the meantime, would you please try some of the troubleshooting steps that I mentioned above? Do let us know if those were helpful. In case you get further doubts then feel free to reach out in the comments. 
Everyone in the community would be happy to help.

I hope you have a great day  😊

**Comment by leecalcote** [comment]
@bluedog13 in short, the most likely challenge that you're facing is one of networking in which Meshery Server attempts to reach Kube API (at `minikube ip`), but can't. There are a handful of approaches to ensuring connectivity between the bridge network that Meshery
 Server is running on. This diagram offers one (not the best solution).

![Bridge networking with Docker deployments of Meshery ](https://user-images.githubusercontent.com/7570704/205678462-e5a3d0d5-0829-45dc-96ad-1137fe066f6d.svg)

**Comment by VedRatan** [comment]
Hi! @bluedog13, I think that you've not tunneled the port 9081, to your localhost port 9081, try this one:
`kubectl port-forward service/meshery 9081:9081 -n meshery`

I guess, this should work.

**Comment by b0id** [comment]
FYI:  I am also a minikube user on Windows side of my machine.  When running `mesheryctl system dashboard`  it redirects to :31104 and I receive `ERR_CONNECTION_REFUSED` . Not sure where this configuration directive is coming from. However when I am implicit to :9081 it does connects to dashboard.  I will follow a few breadcrumbs and see if I can find this on the forum to see if the issue has been fully described.
