### ISSUE TITLE
MeshMap extension not accessible

### ISSUE THREAD

**Issue by deepakdinesh1123** [meshery/meshery#6889]
#### Current Behavior
When I try to open MeshMap I am getting the following error

```
Unknown Error: Error: HTTP Error Response: 404 Not Found (/api/provider/extension/provider/navigator/meshmap/index.js)
```

![Screenshot from 2023-01-14 12-30-10](https://user-images.githubusercontent.com/52698821/212460237-f64b7adb-e507-442e-b429-90af91ab738b.png)

#### Environment

- **Host OS:** Linux
- **Platform:** Docker
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@deepakdinesh1123, thank you for raising this issue! It's not documented (and so you wouldn't be aware), but the MeshMap extension is currently only available on the Meshery `stable` release channel. I commend you for using the Meshery `edge` release. At this time, you'll need to execute `mesheryctl system channel set stable-latest` and `mesheryctl system restart` in order to reboot your deployment on the stable release channel. Alternatively, you can use `mesheryctl system channel switch stable-latest` as a single command to both set and restart your deployment. Please note a bug in the `switch` command was fixed today (https://github.com/meshery/meshery/pull/6892).

If you'd like, we can turn this issue from bug to feature request or we can close this issue (bug report).

**Comment by deepakdinesh1123** [comment]
@leecalcote  Thank you very much for letting me know about this.

**Comment by leecalcote** [comment]
Let's close this issue for now, knowing that availability in the Edge release channel is an ideal enhancement.
