### ISSUE TITLE
[UI] SMI Conformance Modal doesn't populate correctly

### ISSUE THREAD

**Issue by acald-creator** [meshery/meshery#7000]
#### Current Behavior

To access one of the Meshery Adapter features/settings, you can select one of the options to manage your Kubernetes cluster, and also implement service lifecycle.

When selecting SMI Conformance

The modal launched with this:
![Screenshot_20230203_122022](https://user-images.githubusercontent.com/18711313/216678561-10b0fd85-b244-49dd-a0b6-12f3d91b3c70.png)

After clicking different options, the correct display shows up.
![Screenshot_20230203_122057](https://user-images.githubusercontent.com/18711313/216678680-80242fea-1770-403d-93aa-2e8220c53c05.png)

Also the Dark Mode makes it hard to tell which is selected and which one is not.

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by hs05june** [comment]
Hey @leecalcote @acald-creator I was working on this issue. This issue occurs at multiple modals. 

https://user-images.githubusercontent.com/103871275/218160922-c1e7e97c-a723-451d-9925-9638673b88ed.mp4

The modal receives a prop tab which decides what to show. 
![Screenshot from 2023-02-10 23-13-27](https://user-images.githubusercontent.com/103871275/218165947-700c659b-568d-4c81-8cb4-1286b2bdb2bc.png)

Since, React hook useState is used to update the value and it is an asynchronous hook, it doesn't change the state immediately,
It's value is 0 when the modal is rendered.
![Screenshot from 2023-02-10 23-41-12](https://user-images.githubusercontent.com/103871275/218165811-d9b6db46-c57e-4987-ae3e-f75770d1ea40.png)
