### ISSUE TITLE
[Docs] Error codes is not coming on search.

### ISSUE THREAD

**Issue by Harshit-Dandriyal** [meshery/meshery#7050]
#### Current State

<img width="1225" alt="Screenshot 2023-02-10 at 8 48 35 PM" src="https://user-images.githubusercontent.com/56961488/218129563-825c03da-d054-4ff6-bbfa-0e509c7575a3.png">

#### Desired State

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Savio629** [comment]
Can you elaborate the issue @Harshit-Dandriyal ...

**Comment by Harshit-Dandriyal** [comment]
Error codes are the text written in the error section of docs, If you search that text error code in search, you will not get the result, but the text is there. Something wrong with filtering.

**Comment by swagataroy30** [comment]
Hey can i work on this? I am new to this project can you please guide me. Thank You!

**Comment by chinu-anand** [comment]
There is some problem with the currently deployed version of Meshery Docs, in the local env, it's working absolutely fine. 
![image](https://user-images.githubusercontent.com/66985303/218291883-fbab028b-04d8-4ddb-ae95-79ccb0df6da6.png)

**Comment by vishalvivekm** [comment]
This issue still persists @chinu-anand @Harshit-Dandriyal

**Comment by vishalvivekm** [comment]
@Abhishek-kumar09 @asubedy
<em>...continuing from the dev-call</em> :
So we have this error moniker <code>ErrGetLatestReleaseCode</code> in [error-codes](https://docs.meshery.io/reference/error-codes) page,
Here are the results when we search for it:

<strong > in docs running locally</strong> :
<img width="712" alt="Screenshot 2023-04-06 113020" src="https://user-images.githubusercontent.com/110674407/230289847-7a2da4c5-1975-4164-9543-b97b0a2572af.png">

<strong>in deployed version of docs</strong> :
<img width="697" alt="Screenshot 2023-04-06 113112" src="https://user-images.githubusercontent.com/110674407/230289868-f77a849c-197a-40dd-bed8-b7f714d244ae.png">

.....HELP WANTED.....
<em>any tips/suggestions where/which files, I can experiment with, in order to figure/fix this?</em>
