### ISSUE TITLE
[UI] Designer Configurator should use Meshmodel component.

### ISSUE THREAD

**Issue by harkiratsm** [meshery/meshery#7356]
#### Current Behavior

Currently, the designer configurator is using oam interface.

#### Desired Behavior

Since we had moved forward with meshmodel, we need all the categories and components in place for that in the design configurator itself.

#### Implementation

1. Under the [Meshery API endpoints](https://docs.google.com/spreadsheets/d/1ABJCbfQRi0uN_YoP2kmHZ-lTI4S4QuvRk1_unomKNRE/edit#gid=1241442399) doc, you can find meshmodel endpoints.

2. Visit the meshmap playground to find out what you're working on.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Abhishek-kumar09** [comment]
<img width="1367" alt="Screenshot 2023-03-15 at 8 02 38 PM" src="https://user-images.githubusercontent.com/48255244/225341690-7d5ce22e-b9f4-4874-bb8c-ab3f7df04769.png">
<img width="1048" alt="Screenshot 2023-03-15 at 8 02 56 PM" src="https://user-images.githubusercontent.com/48255244/225341800-3781a50b-ff46-4321-b440-4e135243ca21.png">
<img width="1348" alt="Screenshot 2023-03-15 at 8 03 17 PM" src="https://user-images.githubusercontent.com/48255244/225341917-701294f8-3fa7-4f5f-86a1-6750063df35c.png">

Get list of All Models:
https://docs.meshery.io/reference/rest-apis#api-meshmodel-model-get-handle-get-request-for-getting-all-mesh

Get components from a certain Model:
https://docs.meshery.io/reference/rest-apis#api-meshmodel-model-model-component-get-handle-get-request-for

Get certain component from certain model
https://docs.meshery.io/reference/rest-apis#api-meshmodel-model-model-component-name-get-handle-get-request

All the rest API endpoints are available here
https://docs.meshery.io/reference/rest-apis

Its better suited to start from scratch then making the changes in the current functional components. The new component should suit well, because a lot of things has been changed that is not incorporated in the current UI.

**Comment by yash37158** [comment]
LGTM, i can work on this issue @Abhishek-kumar09 @harkiratsm

**Comment by Abhishek-kumar09** [comment]
Thanks for taking this issue, @yash37158 Let me know if you need any help here. You can always be vocal about it in slack or  github issue thread.

**Comment by yash37158** [comment]
Yeah sure

**Comment by yash37158** [comment]
Hey @Abhishek-kumar09 do we have a separate folder for design patterns? where can I see the code for k8s?

**Comment by Abhishek-kumar09** [comment]
The data is loaded dynamically, and the the layout and its state management is being done in React.

Here are some files involved:
1. https://github.com/meshery/meshery/blob/master/ui/components/MesheryPatterns.js
2. https://github.com/meshery/meshery/blob/master/ui/components/configuratorComponents/patternConfigurator.js The UI due to which you're able to see the design-configurator
3.

**Comment by leecalcote** [comment]
@harkiratsm if no one else gets assigned today, then please self-assign this issue.

**Comment by harkiratsm** [comment]
I am taking this on.

**Comment by harkiratsm** [comment]
completed https://github.com/meshery/meshery/pull/7578
