### ISSUE TITLE
[Server] Changing server request for Publishing Catalog Content

### ISSUE THREAD

**Issue by thisiskaransgit** [meshery/meshery#7404]
#### Current Behavior
Currently, the server sends a `200 OK` success status response code when a publish request is submitted.

#### Desired Behavior

Change server to send 202 `Accepted` when a publish request is submitted.

#### Mockups

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Player256** [comment]
@thisiskaransgit I think the fix is here https://github.com/meshery/meshery/blob/81f4b6d1052fa71bbc4b110aa9f88b9d7ec03d6c/server/handlers/meshery_filter_handler.go#L341
Should I change the response in swagger file mentioned in above the function?
https://github.com/meshery/meshery/blob/81f4b6d1052fa71bbc4b110aa9f88b9d7ec03d6c/server/helpers/swagger.yaml#L326C17-L326C17

**Comment by Player256** [comment]
Can I work on this issue @leecalcote ?
