### ISSUE TITLE
Add other useful metrics to the Meshery Playground

### ISSUE THREAD

**Issue by anshgoyalevil** [meshery/meshery#7690]
#### Current Behavior

Inside of the Meshery Playground, there is [Node Exporter](https://github.com/prometheus/node_exporter) running whenever we spin up a cluster, Pod, or things like that, so we only get metrics from Node Exporter, which are useful but to some extent only.

#### Desired Behavior

Other useful metrics need to be added for better monitoring of the cluster and related services.

#### Acceptance Tests

Related tests need to be written and updated.

#### Mockups

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by yash37158** [comment]
I would like to work on this issue @Chadha93 @anshgoyalevil

**Comment by anshgoyalevil** [comment]
Here you go @yash37158 🚀

**Comment by yash37158** [comment]
Thanks, @anshgoyalevil

**Comment by leecalcote** [comment]
@Freedisch fyi...

**Comment by yash37158** [comment]
Do we need to show metrics in the playground or meshery dashboard? if it's on the dashboard we have already got the metrics in meshery's recent release. and if it's in the playground, do we have any design specs for the same? @leecalcote @anshgoyalevil

**Comment by leecalcote** [comment]
@Freedisch, will you chime in here?

**Comment by Freedisch** [comment]
@yash37158, There might be misunderstood here, the node exporter needs a Prometheus instance to display the metrics( which you can do by updating the Meshery settings )
one thing is here to find other alternatives to Node exporter but also compatible with Prometheus because Meshery playground talks Prometheus in order to display the metrics.

Coming back to your question, if u want to display metrics collected by the node exporter you need to connect a Prometheus instance and u will see the results inside the visualizer.

**Comment by yash37158** [comment]
Thanks @Freedisch, for clarification
