### ISSUE TITLE
[Endpoint enhancement] - Return the count of duplicate components

### ISSUE THREAD

**Issue by UsmanDev09** [meshery/meshery#8042]
#### Current Behavior

The endpoint `api/meshmodels/components` does not returns the count of duplicated components. Enhance it to return the count. 

#### Mockups

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
FYI @MUzairS15

**Comment by Seckrel** [comment]
can you be more specific on where the issue is? Are you talking about ui/api/meshmodel.js, if yes, which api function too be specific? I would like to help

**Comment by zakisk** [comment]
@Seckrel Issue is tagged with `language/go` so it won't be in `ui/api/meshmodel.js`.

**Comment by zakisk** [comment]
@UsmanDev09 I would like to work on this.

**Comment by zakisk** [comment]
@UsmanDev09 I looked into the source code thus sharing my insights that how I'm gonna solve the issue is by adding the duplicateComponents field to [this response](https://github.com/meshery/meshery/blob/4506f8489c7f10ef06149a7814fe1448f6538f17/server/models/meshery_meshmodels_api_response.go#L14) model struct and will check for duplicates in [GetAllMeshmodelComponents](https://github.com/meshery/meshery/blob/4506f8489c7f10ef06149a7814fe1448f6538f17/server/handlers/component_handler.go#L1088) in this [loop](https://github.com/meshery/meshery/blob/4506f8489c7f10ef06149a7814fe1448f6538f17/server/handlers/component_handler.go#L1122) and will add to [response](https://github.com/meshery/meshery/blob/4506f8489c7f10ef06149a7814fe1448f6538f17/server/handlers/component_handler.go#L1142).
but I have a question how do you want duplicates in response, whether only the number of duplicates or by their names or IDs or etc, tell me how will I test it I searched for test file for component_handler.go but didn't find it. Thank you

**Comment by UsmanDev09** [comment]
@Seckrel @zakisk Thankyou for showing interest in solving this issue. I think @abdullah1308 is already working on this.

**Comment by leecalcote** [comment]
related - https://github.com/meshery/meshery/issues/6524
