### ISSUE TITLE
[Docs] Expose Meshery API Docs in the App

### ISSUE THREAD

**Issue by theBeginner86** [meshery/meshery#8878]
### Current State

Currently, Meshery API docs are only available at https://docs.meshery.io/reference/rest-apis.

### Desired State

Ensure Meshery API docs are also exposed inside of the Meshery App too through a new UI route `/system/docs`.
This would help Meshery users/contributors to readily explore different Meshery features.

Acceptance Test:
1. Expose a new UI route: `/system/docs`.
2. Add a new command that generates the docs and places the generated under `/public/docs/index.html`
3. Add backend support to serve the static file
4. Use redocly for the process
5. Expose a new menu item under the user avatar menu bar. 'API Docs`
6. Use the docs icon. (you may ask for it in the slack)
7. Add automation to ensure docs are updated on each release.
8. Ensure the automation process updates Meshery latest stable release version in the generated docs.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by EraKin575** [comment]
I would like to work on this

**Comment by AryanSharma9917** [comment]
Hey @theBeginner86, can I work on this?

**Comment by yashlondhe90960** [comment]
Hi @theBeginner86 I would like to work on this!

**Comment by leecalcote** [comment]
@yashlondhe90960 thanks for volunteering. Will you propose a solution here and once verified, let's get you assigned.

**Comment by ptdatta** [comment]
@theBeginner86 @leecalcote If no one is working on it. Can I work on it?

**Comment by Jougan-0** [comment]
@leecalcote @theBeginner86 can i have this issue?

**Comment by ptdatta** [comment]
@theBeginner86 I think this issue is perfect for me as I was looking for some mid-level issues. Yes, the Meshery server runs perfectly.
So far my approach is-
1. Create a menu named `API DOCS`
2. Create an endpoint of `system/docs` pointed by `API DOCS`
3. Using Redocly I will connect it to the documentation Github source and generate the docs.
4. Link the docs to the endpoint.
5. Write a `yaml` file for automation.
 I didn't dive deep into this issue as I'm working on another issue which I almost completed. If assigned I will start working on it tomorrow and share a more detailed approach. I think I can solve it.
