### ISSUE TITLE
[UI] Data Table: Misbehaving activity toolbar

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9012]
### Current Behavior
The standard activity toolbar on data tables has a misbehaving search box.

1. It closes when you click on the (already in focus field), instead of just staying open.
2. It won't close until all table results have returned, so you can't cancel the search mid-flight, but must wait for it to complete.

### Screenshots/Logs
[](https://github.com/meshery/meshery/assets/7570704/52aa41f8-e08e-4368-ab6b-d04eb2924e41)

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by prakashAditya639** [comment]
@leecalcote Can you please assign me this issue under hacktoberfest topic

**Comment by leecalcote** [comment]
@prakashAditya639, yes, however, given that you’ve yet to build, run, or work on Meshery to date and that this needs to be fixed (guaranteed), I’ll ask the you provide a fix before issue assignment so as to avoid it being accidentally squatted on.

**Comment by prakashAditya639** [comment]
@leecalcote Can you please provide the exact location of the issue? on meshery.io

**Comment by leecalcote** [comment]
No, it’s not in Meshery.io. It’s in Meshery UI. 

I feel immediately validated.

**Comment by captain-Akshay** [comment]
@leecalcote can i work on this?

**Comment by captain-Akshay** [comment]
@leecalcote i fixed the first part though & a bit confused about the second part !

[Screencast from 2023-10-05 00-42-51.webm](https://github.com/meshery/meshery/assets/59491379/4e00fbe8-166e-479d-8370-bfb48635f8f7)

-----------------------

for the second part would love to know more because i was able to close the search section even it was fetching it!!

[Screencast from 2023-10-05 00-47-21.webm](https://github.com/meshery/meshery/assets/59491379/e3b6693f-e825-4b19-bd91-1ac7e42ac9ca)

**Comment by captain-Akshay** [comment]
And I will check it in the cloud as soon I get the access 😅✌🏻
