### ISSUE TITLE
[mesheryctl] Failure to import Kubernetes Manifest with `app import`

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#9691]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior
While using a valid kuberenetes manifest (`constraint.yaml`), the `mesheryctl app import` command fails to import the manifest.

```
mesheryctl app import -f constraint.yaml -s manifest
Error: Invalid application source type due to wrong type/passing
```

### Environment

- Host OS: Mac 

```
      	VERSION	GITSHA
Client	v0.7.1 	ef8db2827c
Server	v0.7.3 	Not Set
```

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by shanukun** [comment]
We use the API to retrieve application source types from the server and compare them with the supplied source type in order to verify the source type.

The function `GetApplicationTypes()` in `server/models/meshery_application.go` determines the server response.  
However, it is returning `DesignTypeResponse` rather than the struct `ApplicationTypeResponse`.

These modifications, which were attempted to fix the build errors in commit e7eb5c1d87c5bbc8a075d4c70e811ccc84a6c66b by @theBeginner86, need to be reverted. 

Regarding the build errors, my suggestion is to modify the constant type to string and convert them explicitly to the right type during the struct definition. That way we can also avoid converting those constants to string in multiple places.

**Comment by Adarsh-jaiss** [comment]
Hey @leecalcote , is anyone working on this issue?

**Comment by shanukun** [comment]
@leecalcote Should I make a PR, explaining my suggestion?

**Comment by theBeginner86** [comment]
> @leecalcote Should I make a PR, explaining my suggestion?

Yes, please consider making a PR so that we can discuss over it.

Thanks for digging into the issue. Instead of reverting that specific change we would want to support the new `DesignTypeResponse` in mesheryctl too.
